# Backend CI/CD with Self-hosted Runner
# Always resets EC2 repo to latest GitHub code before deployment

name: Backend CI/CD

on:
  push:
    branches: [ "master" ]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Remove old code
      run: |
        rm -rf ~/ride-on   # wipe old folder to avoid merge conflicts

    - name: Checkout repo into ~/ride-on
      uses: actions/checkout@v4
      with:
        path: ~/ride-on

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd ~/ride-on/backend
        npm install

    - name: Deploy backend
      run: |
        cd ~/ride-on/backend
        npm install --production
        pm2 restart rideon-server || pm2 start server.js --name rideon-server
